### ISSUE TITLE
Doesn't appear to reliably work on Fedora Linux

### ISSUE THREAD

**Issue by cfeller** [fastaddons/Darko#12]
I've installed Darko on three (3) separate installations of Thunderbird 78.5 on Fedora 32. Initially installing the Darko extension appeared to have no effect. That is, the messages still contained black text and white background. 

After toggling the plugin off/on several times, restarting the browser, even removing and reinstalling the plugin, the extension started working on one of the machines. On the other two machines it appears to not be working.

Not sure the best way to debug this

**Comment by Juraj-Masiar** [comment]
Hello,
Any chance this is related to the Vertical view issue: https://github.com/fastaddons/Darko/issues/10?
If yes, then there is a good news, the new Thunderbird 78.6 will fix this and should be released next week.

**Comment by fazaldegui** [comment]
It doesn't work for me either. But running in Windows 10 version 20H2 and the same version of Thunderbird 78.5.1 (64-bits).
I'll wait next week to the 78.6 and see if it's fixed.

**Comment by fastaddons** [comment]
But do you use the Vertical view?
![Screenshot 2020-12-10 14 02 14](https://user-images.githubusercontent.com/55486931/101775894-7128e680-3af0-11eb-9861-dc50b534c049.png)
Press "Alt" key to show the menu bar and check the "View / Layout"

**Comment by fazaldegui** [comment]
No, I use classic view. But I tried the others layouts and no luck.
Also if I open the message in a new tab it is white.
I click several times to the Darko icon but no luck.

**Comment by fastaddons** [comment]
Thanks for the info! So let's see next week after the release.
It it doesn't help, please let me know and I will install Fedora and test it there.
But it should work without any issues, I'm testing my addons on latest Windows and Ubuntu and OS-specific bugs are very rare.

**Comment by cfeller** [comment]
I am using classic view

However, I did some tinkering based off of the above comments... This is interesting:

Changing the view from classic to vertical or to vertical to classic fixes it temporarily. That is, it fixes it in the running instance. Upon restart it is broken again. 

Interestingly, this also allows Darko to be used in the vertical view - that is, it fixes it (it works) in the vertical view as well albeit temporarily.  So not sure if this issue is somehow related to #10

**Comment by fastaddons** [comment]
Thanks @cfeller, I'm 99% sure this is the same bug and it will be fixed with the new Thunderbird. It should be released on Tuesday but sometimes they are few days late.

**Comment by fastaddons** [comment]
New version 78.6.0 was just released - you can click the main menu / Help / About Thunderbird, to check for update.
Please let me know if the issue is fixed in the new version.
Thanks!

**Comment by cfeller** [comment]
All appears to be good with 78.6.0!

**Comment by localjo** [comment]
I'm having this problem with Thunderbird 78.6.1 on macOS. The layout doesn't seem to matter. I see the toolbar item, and it shows that Darko is active, but all of my messages (HTML and plain text) are still white background with black text. I've restarted many times, and it's still not working.

Are there any settings that Darko is dependent on? Anything I can try to debug?

**Comment by fastaddons** [comment]
@localjo I've created new issue, let's discuss it there.
