### ISSUE TITLE
Darko doesn't seem to work in MacOS

### ISSUE THREAD

**Issue by fastaddons** [fastaddons/Darko#13]
I'm having this problem with Thunderbird 78.6.1 on macOS. The layout doesn't seem to matter. I see the toolbar item, and it shows that Darko is active, but all of my messages (HTML and plain text) are still white background with black text. I've restarted many times, and it's still not working.

Are there any settings that Darko is dependent on? Anything I can try to debug?

_Originally posted by @localjo in https://github.com/fastaddons/Darko/issues/12#issuecomment-760758161_

**Comment by fastaddons** [comment]
So the addon itself is super simple so there is not much that can go wrong and most bugs is related to Thunderbird issues.
Sadly I don't have access to my office right now due to lockdown so I can't test it in my testing MacOS.

But maybe you could help here. Please do this:
1) open any email
2) open "Error console" - form the main menu / Tools / Developer tools / Error console.
3) click the Darko toolbar icon
When the icon in the toolbar is yellow moon, it's active and email should get dark. If it's gray wolf, it's inactive and email should get white.
If it doesn't work, check the error console to see if there are some new errors.

**Comment by localjo** [comment]
When the icon is a yellow moon, and I click on it, it becomes a gray wolf and then I see this error in the console:

```
this.messageManager is null                                                                                          MessageChannel.jsm:208
    FilteringMessageManager resource://gre/modules/MessageChannel.jsm:208
    ResponseManager resource://gre/modules/MessageChannel.jsm:310
    get resource://gre/modules/MessageChannel.jsm:459
    sendMessage resource://gre/modules/MessageChannel.jsm:879
    sendMessage resource://gre/modules/ExtensionCommon.jsm:691
    sendMessage chrome://extensions/content/parent/ext-tabs-base.js:106
    _execute chrome://extensions/content/parent/ext-tabs-base.js:758
    removeCSS chrome://extensions/content/parent/ext-tabs-base.js:811
    removeFromWindow chrome://messenger/content/parent/ext-extensionScripts.js:168
    destroy chrome://messenger/content/parent/ext-extensionScripts.js:97
    unregister chrome://messenger/content/parent/ext-extensionScripts.js:213
    unregister self-hosted:844
    result resource://gre/modules/ExtensionParent.jsm:996
    withPendingBrowser resource://gre/modules/ExtensionParent.jsm:602
    result resource://gre/modules/ExtensionParent.jsm:996
    callAndLog resource://gre/modules/ExtensionParent.jsm:958
    recvAPICall resource://gre/modules/ExtensionParent.jsm:995
    AsyncFunctionNext self-hosted:693
Uncaught (in promise) Error: An unexpected error occurred                                                               undefined
```

I don't see any errors when I switch the other direction.

**Comment by fastaddons** [comment]
So, something is definitely wrong, but this stack trace is all Thunderbird code, it may be better to report it to Thunderbird directly.

Is there something special about your Thunderbird?
Did you tried to "fully restart" your Thunderbird? Try to right click the Thunderbird in the toolbar and select "Close" (or kill or something like that). Sometimes restarting whole PC helps.
You can also try to uninstall the addon, then restart Thunderbird and then install it back again.

Anyway, in my Thunderbird store I can see the addon is used by 74 MacOS users, so it really should work else more people would complain.

**Comment by localjo** [comment]
After poking around some more, it looks like this is a conflict with the [Thunderbird Conversations](https://github.com/thunderbird-conversations/thunderbird-conversations) add-on. I will investigate further. It's pretty hard for me to give up threaded conversation view in Thunderbird.

**Comment by fastaddons** [comment]
Ah, yes, this is unfortunate. 
Addons cannot run inside another addon. So this will never work :(
The only "solution" would be if author of the "Thunderbird Conversations" build dark mode himself...

**Comment by lf-** [comment]
I am having a similar issue on arch linux with Thunderbird 78.8.0. No other addons. It seems like Darko is just not doing anything regardless of what icon it shows in the top bar, and I'm not sure why. I am relatively familiar with web development tools. Is there some information I can get that would be of use? I don't seem to see Darko printing anything incriminating to the console.

Edit: ohohohoho it's a recurrence of the #12 vertical view thing. works good now when I changed the view like that.

**Comment by fastaddons** [comment]
Hello @lf- . Are you sure? That bug should have been fixed in Thunderbird for some time now.
When you switch back now to Vertical view, is it still gonna be broken? Please try. If yes, then we should mention it in the original bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1674932

**Comment by lf-** [comment]
Naturally as soon as I got it working, I cannot reproduce the original problem. I wonder if it requires switching the mode at least once so that Darko works properly? Weird as heck! You know what's even stranger though? I moved my `.thunderbird` directory to another one and recreated the profile and could not reproduce the bug. Going to call this one a heisenbug to be honest...

**Comment by jackblk** [comment]
With Thunderbird 91, this issue seems to be fixed. Previously I have this problem for months, but now I don't see it even once 😄
