### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by vicojam** [fastaddons/Darko#14]
Lamentablemente ya no es funcional

**Comment by fastaddons** [comment]
There seems to be some issues in the Thunderbird:
https://bugzilla.mozilla.org/show_bug.cgi?id=1707573

Could you try the Dark Reader to see if that one will work?
https://addons.thunderbird.net/thunderbird/addon/darkreader/

**Comment by wvxwxvw** [comment]
Now it works, you can close it. A wonderful extension, I just switched to 91 and tried to do something myself with styles, but I didn’t come up with anything smarter than the general muting of colors `html { background-color: rgba`.
