### ISSUE TITLE
Darko is not dark in Thunderbird

### ISSUE THREAD

**Issue by panther7** [fastaddons/Darko#21]
**Describe the bug**  
Darko is not dark, but lightgrey

**Expected behavior**  
Darkner: darkgrey

**Device info:**
 - operating system: win 11
 - Browser and version: thunderbird 102.0b3
 - addon version: 3.3

![2022-06-07 15 44 09](https://user-images.githubusercontent.com/3808250/172395725-1e4832b1-4b44-46eb-9566-4cfb53227d4b.png)

**Comment by fastaddons** [comment]
That's crazy :)
Are you using also some other dark-mode addon?
Or maybe new Thunderbird has own dark mode now?
Or did you changed the default background color for the emails in the Thunderbird color settings?

**Comment by panther7** [comment]
Only Darko,
Thunderbird have darkmode for UI, not for emails.
Default backgroud color is default.

You can try TB 102 on your computer.

I think, that works in 101 (but i dont sure)

**Comment by fastaddons** [comment]
Hmm, I can see it now, it affects only some emails though, that's strange.
And it seems the "Dark Reader" works fine, so this is some styling compatibility issue in my addon, that's not good.

Oh man, I have like 0 free time right now, I'm not sure I will be able to fix this. Especially when there is a better alternative - the Dark Reader addon. This may be the end of Darko.

**Comment by panther7** [comment]
Yes, Dark Reader works... thanks for suggestion, i moved on it and thanks for works on Darko :)
