### ISSUE TITLE
Autostart Darko

### ISSUE THREAD

**Issue by RoseVampirex** [fastaddons/Darko#26]
**Is your feature request related to a problem? Please describe.**
Not a problem, but a quality of life feature. Any time I open Thunderbird, Darko defaults to light mode, even if I switched it to dark mode earlier and closed, then reopened the program.

**Describe the solution you'd like**
Could you add an option for Darko to stay in light or dark mode after reopening Thunderbird? This will depend on which setting Darko was on before closing the program.

For example:

Open Thunderbird, Darko is in light mode.
Click on the Darko button to switch to dark mode.
Close Thunderbird.
Open Thunderbird, Darko is in dark mode. 

or vice versa. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Juraj-Masiar** [comment]
The dark mode is the default, so you have light mode when you start Thunderbird, then something is turning it off.
I would guess you have a scheduler enabled - see Darko Options page (double click the darko toolbar icon) and then check "Automatic dark mode" section and make sure it's not enabled.

**Comment by RoseVampirex** [comment]
That's exactly what it was, sorry about that!
