### ISSUE TITLE
Exclude images?

### ISSUE THREAD

**Issue by fastaddons** [fastaddons/Darko#3]
Maybe I should exclude images from the color inversion because some pictures, especially human photos will look scary!

![m64RrZJ9hoVJuMFgsbQCAZ](https://user-images.githubusercontent.com/55486931/98866988-1a3add80-246e-11eb-91bc-2dcc6491b982.jpg)

![Screenshot 2020-11-11 22 30 36](https://user-images.githubusercontent.com/55486931/98866943-05f6e080-246e-11eb-9fdb-a270047f089d.png)

**Comment by liurui39660** [comment]
Instead of simply inverting them, maybe lowering the brightness and/or contrast can be more helpful.

**Comment by fastaddons** [comment]
New version 2.0 was just released with by-default disabled color inversion for images.
I have also added contrast option (brightness filter doesn't work as one would expect so I didn't included it).

New Options page can be opened by double-click on the Darko icon!
